2024-11-04 17:14:12,328 - root - ERROR - table_creator.py:51 - Error al crear las tablas: (mysql.connector.errors.ProgrammingError) 1049 (42000): Unknown database 'madyboonnector.errors.ProgrammingError) 1049 (42000): Unknown database 'madybot_db'
(Background on this error at: https://sqlalche.me/e/20/f405)

Falta crear base de datos en caso de que no exista

2024-11-05 20:02:59,623 - root - ERROR - El archivo de icono 'C:\AppServ\www\MadyBot_Py\static\favicon.ico' no existe.